### PR TITLE
reset

### LINKED ISSUE #10: Feruz: Reset
- [x] create branch (reset)
- [x] create handler reset.js
- [x] create listener reset.js

* what will happen in this function
> score will be 0
>  make log empty 
>  Like refresh you page

### PR DESCRIPTION
**Pull request by Feruzteame**
closes #10 
easy function 😄

### CODE REVIEW

**Review by aleks2407 — APPROVED** [review]
I didn't know about this way to reset honestly. I wrote a function that is  way longer))))Using a for loop. nice! :)

**Comment by Feruzteame** [comment]
It works ! For the next time do not write long reset function. :smile:

**Comment by miroslavveljanoski** [comment]
> I didn't know about this way to reset honestly. I wrote a function that is way longer))))Using a for loop. nice! :)

hey @Feruzteame @aleks2407 I'm not sure how are you checking if this function works?

**Comment by Feruzteame** [comment]
That's why we are waiting to @yaredyilma .
Actually many times i use it.

**Comment by aleks2407** [comment]
@miroslavveljanoski no, i didn't check this one. there is no way right now to check it on our project))) so I just trust Feruz, as she says that it works. I thought this function should update the state using the loop

**Comment by Feruzteame** [comment]
You can check here. https://feruzteame.github.io/Quiz/start.html

**Review by miroslavveljanoski — APPROVED** [review]

**Pull request merged**
